name: CI

on: push

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump vars context
        run: echo "${{ toJson(vars) }}"
      - name: Dump env context
        run: echo "${{ toJson(env) }}"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
  two:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: noop
        run: tree -a

  three:
    runs-on: ubuntu-latest
    needs:
      - one
      - two
    steps:
      - name: Dump needs context
        env:
          NEEDS_CONTEXT: ${{ toJson(needs) }}
        run: |
          echo "$NEEDS_CONTEXT" | jq -jr 'to_entries[] | .key, ": ", .value.result, "\n"'
      - name: Dump vars context
        run: echo "${{ toJson(vars) }}"
      - name: Dump env context
        run: echo "${{ toJson(env) }}"
