---
name: Needs with Matrix

on:
  push:
    branches:
      - main

jobs:
  matrix:
    continue-on-error: true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: [1, 2, 3]
    steps:
      - name: Hello
        run: |
          echo "Hello ${{ matrix.value }}"
          [[ "${{ matrix.value }}" = "2" ]] && exit 1 || exit 0
  needs:
    runs-on: ubuntu-latest
    needs: matrix
    if: always()
    steps:
      - name: Dump needs context
        env:
          NEEDS_CONTEXT: ${{ toJson(needs) }}
        run: echo "$NEEDS_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
