---
name: Needs with Matrix

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stage: [one, two, three]
    steps:
      - name: Decide if we should run
        id: decision
        run: |
          if [[ "${{ matrix.stage }}" == "two" ]]; then
            echo "needed=false" >> $GITHUB_OUTPUT
          else
            echo "needed=true" >> $GITHUB_OUTPUT
          fi
      - name: Dump needs context
        if: steps.decision.outputs.needed == 'true'
        env:
          NEEDS_CONTEXT: ${{ toJson(needs) }}
        run: echo "$NEEDS_CONTEXT"
      - name: Dump job context
        if: steps.decision.outputs.needed == 'true'
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        if: steps.decision.outputs.needed == 'true'
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump strategy context
        if: steps.decision.outputs.needed == 'true'
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        if: steps.decision.outputs.needed == 'true'
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
