---
name: Needs with Matrix

on:
  push:
    branches:
      - main

jobs:
  matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: [1, 2, 3]
    outputs:
      needed: ${{ steps.check.outputs.needed }}
    steps:
      - name: Check value
        id: check
        run: |
          echo "Hello ${{ matrix.value }}"
          if [[ "${{ matrix.value }}" = "2" ]]; then
            echo "::set-output name=needed::false"
          else
            echo "::set-output name=needed::true"
          fi
  needs:
    runs-on: ubuntu-latest
    needs: matrix
    steps:
      - name: Dump needs context
        env:
          NEEDS_CONTEXT: ${{ toJson(needs) }}
        run: echo "$NEEDS_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
