---
name: Print Contexts

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  multiline-expression:
    runs-on: ubuntu-latest
    steps:
      - name: test multiline expression
        run: |
          echo '${{ github.ref_name == github.event.repository.default_branch && "Powerful" || "Powerless" }}'
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump vars context
        run: echo "${{ toJson(vars) }}"
      - name: Dump env context
        run: echo "${{ toJson(env) }}"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
